// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAfVg-Ps66XU8tVKqMR4oexqRSewqIEe-M',
    appId: '1:473902429159:web:57f5a538f49d03a33b8342',
    messagingSenderId: '473902429159',
    projectId: 'aolo-cabs',
    authDomain: 'aolo-cabs.firebaseapp.com',
    databaseURL: 'https://aolo-cabs-default-rtdb.firebaseio.com',
    storageBucket: 'aolo-cabs.firebasestorage.app',
    measurementId: 'G-VYD8NFSMXW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD1RTL67E6Ve7dR0lI16ZDw8WKDs0DKlak',
    appId: '1:473902429159:android:735021f23168b6b53b8342',
    messagingSenderId: '473902429159',
    projectId: 'aolo-cabs',
    databaseURL: 'https://aolo-cabs-default-rtdb.firebaseio.com',
    storageBucket: 'aolo-cabs.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCQAv6Nt9g5WYrvSNrGkLwyFCBn5bIPx0U',
    appId: '1:473902429159:ios:07c1165c0de98e5f3b8342',
    messagingSenderId: '473902429159',
    projectId: 'aolo-cabs',
    databaseURL: 'https://aolo-cabs-default-rtdb.firebaseio.com',
    storageBucket: 'aolo-cabs.firebasestorage.app',
    iosBundleId: 'com.aolocabs.user',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCQAv6Nt9g5WYrvSNrGkLwyFCBn5bIPx0U',
    appId: '1:473902429159:ios:7d9231c443ffdb2c3b8342',
    messagingSenderId: '473902429159',
    projectId: 'aolo-cabs',
    databaseURL: 'https://aolo-cabs-default-rtdb.firebaseio.com',
    storageBucket: 'aolo-cabs.firebasestorage.app',
    iosBundleId: 'com.aolo.users.users',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBJY9Q-2vqhjOfRDB19T3lkRQ-QKAvKsi0',
    appId: '1:473902429159:web:30bde9b7805f8aa83b8342',
    messagingSenderId: '473902429159',
    projectId: 'aolo-cabs',
    authDomain: 'aolo-cabs.firebaseapp.com',
    databaseURL: 'https://aolo-cabs-default-rtdb.firebaseio.com',
    storageBucket: 'aolo-cabs.firebasestorage.app',
    measurementId: 'G-055Z6FEWFH',
  );
}
